# Example GitHub Actions workflow: Filter bibliography to cited entries
#
# Copy this file to your repository's .github/workflows/ directory
# to automatically filter your bibliography when .tex or .bib files change.
#
# This workflow downloads filter_bibliography.py and runs it locally.
# No pip dependencies required - filter_bibliography.py uses only Python stdlib.

name: Filter Bibliography

on:
  push:
    paths:
      - '**.bib'
      - '**.tex'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  filter:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download filter script
        run: |
          curl -fsSL https://raw.githubusercontent.com/rpatrik96/bibtexupdater/main/filter_bibliography.py -o filter_bibliography.py

      - name: Filter bibliography
        run: |
          # Adjust paths to match your project:
          # - First argument: directory or .tex files to scan
          # - -b: input bibliography file(s)
          # - -o: output filtered bibliography
          python filter_bibliography.py . -b references.bib -o references.bib -r --no-warn-missing

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: filter bibliography to cited entries"
          git push
